name: Potential Duplicates
on:
  issues:
    types: [opened, edited]
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: wow-actions/potential-duplicates@v1.0.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
